'use client'
import { useState, useEffect, useRef } from 'react'
import { DndContext, closestCenter, PointerSensor, useSensor, useSensors, DragEndEvent } from '@dnd-kit/core'
import { SortableContext, verticalListSortingStrategy, useSortable, arrayMove } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { useUser } from '@clerk/nextjs'
import { Song, PlaylistSong, ClassBlock } from '@/lib/types'
import { generateTemplate, BLOCK_COLORS } from '@/lib/classTemplates'
import { Movement, MOVEMENTS, getMovementsForBlock, bpmRangeFromMovements, calcTargetBpm } from '@/lib/movements'
import SongCard from '@/components/SongCard'
import SpotifyPlaylistPicker from '@/components/SpotifyPlaylistPicker'

const MAT_EQUIPMENT = [
  { id: 'mat', label: 'Mat', emoji: '🟩' },
  { id: 'theraband', label: 'Theraband', emoji: '🎗️' },
  { id: 'magic-circle', label: 'Magic Circle', emoji: '⭕' },
  { id: 'small-ball', label: 'Small Ball', emoji: '🔵' },
  { id: 'foam-roller', label: 'Foam Roller', emoji: '🪵' },
  { id: 'weights', label: 'Hand Weights', emoji: '🏋️' },
  { id: 'block', label: 'Yoga Block', emoji: '🧱' },
  { id: 'strap', label: 'Stretch Strap', emoji: '🪢' },
]

const REFORMER_EQUIPMENT = [
  { id: 'reformer', label: 'Reformer', emoji: '⚙️' },
  { id: 'box', label: 'Long/Short Box', emoji: '📦' },
  { id: 'jump-board', label: 'Jump Board', emoji: '🦘' },
  { id: 'magic-circle', label: 'Magic Circle', emoji: '⭕' },
  { id: 'pole', label: 'Pole / Dowel', emoji: '🪄' },
  { id: 'theraband', label: 'Theraband', emoji: '🎗️' },
  { id: 'weights', label: 'Hand Weights', emoji: '🏋️' },
  { id: 'platform-extender', label: 'Platform Extender', emoji: '📐' },
]

const BLOCK_EMOJIS = ['🌅','🧍','💪','🔥','🧘','⚡','🌊','🎯','🏃','🌿','✨','🦋','🌸','🎵','🏆']
const COLOR_KEYS = Object.keys(BLOCK_COLORS)

function isCustomBlock(blockId: string) {
  return blockId.startsWith('custom-')
}

// ─── PDF Export ───────────────────────────────────────────────────────────────
async function loadJsPDF(): Promise<any> {
  if ((window as any).jspdf?.jsPDF) return (window as any).jspdf.jsPDF
  return new Promise((resolve, reject) => {
    const script = document.createElement('script')
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
    script.onload = () => resolve((window as any).jspdf.jsPDF)
    script.onerror = reject
    document.head.appendChild(script)
  })
}

async function exportToPDF(className: string, setup: { format: 'mat' | 'reformer'; duration: number; level: string }, blocks: ClassBlock[], blockMovements: Record<string, Movement[]>, blockNotes: Record<string, string>, equipment: Set<string>) {
  const jsPDF = await loadJsPDF()
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = 210, pageH = 297, margin = 20, contentW = pageW - margin * 2
  let y = margin
  const GREEN = [76, 130, 76], DARK = [30, 50, 30], GRAY = [100, 110, 100], LIGHTGRAY = [220, 228, 220], WHITE = [255, 255, 255]
  function checkPage(needed = 20) { if (y + needed > pageH - margin) { doc.addPage(); y = margin } }
  function drawLine(color = LIGHTGRAY) { doc.setDrawColor(...(color as [number, number, number])); doc.setLineWidth(0.3); doc.line(margin, y, pageW - margin, y); y += 4 }
  doc.setFillColor(...(GREEN as [number, number, number])); doc.rect(0, 0, pageW, 28, 'F')
  doc.setTextColor(...(WHITE as [number, number, number])); doc.setFontSize(20); doc.setFont('helvetica', 'bold'); doc.text(className, margin, 13)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal')
  doc.text(`${setup.format === 'mat' ? 'Mat Pilates' : 'Reformer Pilates'} · ${setup.duration} min · ${setup.level.charAt(0).toUpperCase() + setup.level.slice(1)}`, margin, 21)
  doc.setFontSize(8); doc.text(`Generated by Pilates Music Builder · ${new Date().toLocaleDateString()}`, pageW - margin, 21, { align: 'right' })
  y = 36
  const totalSeconds = blocks.reduce((acc, b) => acc + b.songs.reduce((a, s) => a + (s.duration ?? 0), 0), 0)
  const totalMins = Math.floor(totalSeconds / 60), totalSecs = String(totalSeconds % 60).padStart(2, '0')
  const allSongs = blocks.flatMap(b => b.songs)
  const avgBpm = allSongs.length ? Math.round(allSongs.reduce((a, s) => a + s.bpm, 0) / allSongs.length) : 0
  doc.setFillColor(...(LIGHTGRAY as [number, number, number])); doc.roundedRect(margin, y, contentW, 12, 2, 2, 'F')
  doc.setTextColor(...(DARK as [number, number, number])); doc.setFontSize(9); doc.setFont('helvetica', 'bold')
  doc.text(`Total Duration: ${totalMins}:${totalSecs}`, margin + 4, y + 8)
  if (avgBpm > 0) doc.text(`Avg BPM: ${avgBpm}`, margin + contentW / 2, y + 8)
  doc.text(`Total Songs: ${allSongs.length}`, margin + contentW - 4, y + 8, { align: 'right' }); y += 18
  const equipmentList = Array.from(equipment).map(id => (setup.format === 'mat' ? MAT_EQUIPMENT : REFORMER_EQUIPMENT).find(e => e.id === id)?.label).filter(Boolean)
  if (equipmentList.length > 0) {
    doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(...(GREEN as [number, number, number])); doc.text('EQUIPMENT NEEDED', margin, y); y += 5
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(...(DARK as [number, number, number])); doc.text(equipmentList.join('  ·  '), margin, y); y += 8; drawLine()
  }
  for (const block of blocks) {
    const movements = blockMovements[block.id] ?? [], note = blockNotes[block.id] ?? ''
    const bSecs = block.songs.reduce((a, s) => a + (s.duration ?? 0), 0)
    const bMins = Math.floor(bSecs / 60), bSec = String(bSecs % 60).padStart(2, '0')
    const blockBpm = block.songs.length > 0 ? Math.round(block.songs.reduce((a, s) => a + s.bpm, 0) / block.songs.length) : null
    checkPage(30)
    doc.setFillColor(...(GREEN as [number, number, number])); doc.roundedRect(margin, y, contentW, 10, 2, 2, 'F')
    doc.setTextColor(...(WHITE as [number, number, number])); doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.text(block.name, margin + 4, y + 7)
    doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.text(`${bMins}:${bSec}${blockBpm ? ` · avg ${blockBpm} BPM` : ''} · ${block.songs.length} tracks`, pageW - margin - 4, y + 7, { align: 'right' }); y += 14
    if (movements.length > 0) { checkPage(10); doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(...(GREEN as [number, number, number])); doc.text('Movements:', margin + 2, y); doc.setFont('helvetica', 'normal'); doc.setTextColor(...(GRAY as [number, number, number])); const movLines = doc.splitTextToSize(movements.map(m => m.name).join('  ·  '), contentW - 30); doc.text(movLines, margin + 25, y); y += movLines.length * 4 + 3 }
    if (note.trim()) { checkPage(10); doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(...(GREEN as [number, number, number])); doc.text('Notes:', margin + 2, y); doc.setFont('helvetica', 'italic'); doc.setTextColor(...(GRAY as [number, number, number])); const noteLines = doc.splitTextToSize(note, contentW - 20); doc.text(noteLines, margin + 18, y); y += noteLines.length * 4 + 3 }
    if (block.songs.length === 0) { doc.setFontSize(8); doc.setFont('helvetica', 'italic'); doc.setTextColor(...(LIGHTGRAY as [number, number, number])); doc.text('No songs added to this block', margin + 4, y); y += 6 }
    else { for (let i = 0; i < block.songs.length; i++) { const song = block.songs[i]; const dur = song.duration ?? 0; const m = Math.floor(dur / 60); const s = String(dur % 60).padStart(2, '0'); checkPage(7); if (i % 2 === 0) { doc.setFillColor(245, 250, 245); doc.rect(margin, y - 3, contentW, 7, 'F') } doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(...(DARK as [number, number, number])); doc.text(`${i + 1}.`, margin + 2, y + 2); const title = song.title ?? song.name ?? ''; doc.text(title.length > 35 ? title.substring(0, 35) + '...' : title, margin + 8, y + 2); doc.setFont('helvetica', 'normal'); doc.setTextColor(...(GRAY as [number, number, number])); doc.text(song.artist, margin + 85, y + 2); doc.setFont('helvetica', 'bold'); doc.setTextColor(...(GREEN as [number, number, number])); doc.text(`${song.bpm} BPM`, pageW - margin - 20, y + 2); doc.setFont('helvetica', 'normal'); doc.setTextColor(...(GRAY as [number, number, number])); doc.text(`${m}:${s}`, pageW - margin - 4, y + 2, { align: 'right' }); y += 7 } }
    y += 4; drawLine()
  }
  doc.setFontSize(7); doc.setTextColor(...(LIGHTGRAY as [number, number, number])); doc.text('Pilates Music Builder · pilates-music-builder.vercel.app', pageW / 2, pageH - 8, { align: 'center' })
  doc.save(`${className.replace(/[^a-z0-9]/gi, '_')}_class_plan.pdf`)
}

// ─── Energy Arc ───────────────────────────────────────────────────────────────
function EnergyArc({ blocks, blockMovements }: { blocks: ClassBlock[]; blockMovements: Record<string, Movement[]> }) {
  if (blocks.length < 2) return null
  const bpms = blocks.map(b => {
    const movements = blockMovements[b.id] ?? []
    if (b.songs.length > 0) return Math.round(b.songs.reduce((a, s) => a + s.bpm, 0) / b.songs.length)
    if (movements.length > 0) return calcTargetBpm(movements)
    return Math.round((b.bpmMin + b.bpmMax) / 2)
  })
  const W = 280, H = 64, PAD = 8
  const innerW = W - PAD * 2, innerH = H - PAD * 2
  const minBpm = Math.min(...bpms) - 5, maxBpm = Math.max(...bpms) + 5, range = maxBpm - minBpm || 1
  const points = bpms.map((bpm, i) => ({ x: PAD + (i / (blocks.length - 1)) * innerW, y: PAD + innerH - ((bpm - minBpm) / range) * innerH }))
  const pathD = points.reduce((acc, pt, i) => { if (i === 0) return `M ${pt.x} ${pt.y}`; const prev = points[i - 1]; const cpX = (prev.x + pt.x) / 2; return `${acc} C ${cpX} ${prev.y}, ${cpX} ${pt.y}, ${pt.x} ${pt.y}` }, '')
  const fillD = `${pathD} L ${points[points.length - 1].x} ${H} L ${points[0].x} ${H} Z`
  const hasSongs = blocks.some(b => b.songs.length > 0)
  return (
    <div>
      <svg width={W} height={H} viewBox={`0 0 ${W} ${H}`} className="w-full overflow-visible">
        <defs><linearGradient id="arcGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6b9e6b" stopOpacity="0.3"/><stop offset="100%" stopColor="#6b9e6b" stopOpacity="0.02"/></linearGradient></defs>
        <path d={fillD} fill="url(#arcGradient)"/>
        <path d={pathD} fill="none" stroke={hasSongs ? '#5a8f5a' : '#c8d5c8'} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
        {points.map((pt, i) => <circle key={i} cx={pt.x} cy={pt.y} r="4" fill={blocks[i].songs.length > 0 ? '#5a8f5a' : '#c8d5c8'} stroke="white" strokeWidth="1.5"/>)}
      </svg>
      <div className="flex justify-between mt-1 px-1">
        {blocks.map((b, i) => (
          <div key={b.id} className="flex flex-col items-center gap-0.5" style={{ width: `${100 / blocks.length}%` }}>
            <span className="text-xs font-mono text-sage-500">{bpms[i]}</span>
            <span className="text-xs">{b.emoji}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── Setup Screen ─────────────────────────────────────────────────────────────
function SetupScreen({ onStart, savedClasses, onLoad, onDelete }: {
  onStart: (f: 'mat' | 'reformer', d: number, l: 'beginner' | 'intermediate' | 'advanced') => void
  savedClasses: any[]; onLoad: (saved: any) => void; onDelete: (id: string) => void
}) {
  const [format, setFormat] = useState<'mat' | 'reformer'>('mat')
  const [duration, setDuration] = useState(55)
  const [level, setLevel] = useState<'beginner' | 'intermediate' | 'advanced'>('intermediate')
  const [deletingId, setDeletingId] = useState<string | null>(null)
  async function handleDelete(id: string) { setDeletingId(id); await onDelete(id); setDeletingId(null) }
  return (
    <div className="max-w-2xl mx-auto py-10 px-4">
      <div className="text-center mb-10">
        <h2 className="font-display text-3xl font-bold text-sage-900 mb-2">Build Your Class</h2>
        <p className="text-sage-500">Tell us about your class and we'll structure it for you</p>
      </div>
      {savedClasses.length > 0 && (
        <div className="mb-8">
          <label className="block text-sm font-semibold text-sage-700 mb-3">Saved Classes</label>
          <div className="space-y-2">
            {savedClasses.map(c => (
              <div key={c.id} className="flex items-center gap-2 px-4 py-3 rounded-xl border border-cream-300 bg-white hover:border-sage-300 transition-all">
                <button onClick={() => onLoad(c)} className="flex-1 text-left">
                  <p className="font-semibold text-sage-800 text-sm">{c.name}</p>
                  <p className="text-xs text-sage-400 mt-0.5">{c.format === 'mat' ? '🧘 Mat' : '⚙️ Reformer'} · {c.duration} min · {c.level} · {new Date(c.updated_at).toLocaleDateString()}</p>
                </button>
                <button onClick={() => handleDelete(c.id)} disabled={deletingId === c.id}
                  className="shrink-0 w-8 h-8 flex items-center justify-center rounded-lg text-sage-300 hover:text-red-400 hover:bg-red-50 transition-all">
                  {deletingId === c.id ? <span className="text-xs">...</span> : <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2"><path d="M2 2l10 10M12 2L2 12"/></svg>}
                </button>
                <button onClick={() => onLoad(c)} className="shrink-0 text-sage-400 text-sm hover:text-sage-600">Load →</button>
              </div>
            ))}
          </div>
          <div className="flex items-center gap-3 my-6"><div className="flex-1 h-px bg-cream-300"/><span className="text-xs text-sage-400">or start fresh</span><div className="flex-1 h-px bg-cream-300"/></div>
        </div>
      )}
      <div className="mb-8">
        <label className="block text-sm font-semibold text-sage-700 mb-3">Class Format</label>
        <div className="grid grid-cols-2 gap-3">
          {([{ value: 'mat', label: 'Mat Pilates', emoji: '🧘', desc: 'Floor-based, flowing movement' }, { value: 'reformer', label: 'Reformer Pilates', emoji: '⚙️', desc: 'Machine-based, resistance work' }] as const).map(f => (
            <button key={f.value} onClick={() => setFormat(f.value)} className={`p-5 rounded-2xl border-2 text-left transition-all ${format === f.value ? 'border-sage-500 bg-sage-50' : 'border-cream-300 bg-white hover:border-sage-300'}`}>
              <div className="text-2xl mb-2">{f.emoji}</div>
              <div className="font-semibold text-sage-900 text-sm">{f.label}</div>
              <div className="text-xs text-sage-400 mt-0.5">{f.desc}</div>
            </button>
          ))}
        </div>
      </div>
      <div className="mb-8">
        <label className="block text-sm font-semibold text-sage-700 mb-3">Class Duration</label>
        <div className="grid grid-cols-4 gap-2">
          {[45, 50, 55, 60].map(d => (
            <button key={d} onClick={() => setDuration(d)} className={`py-3 rounded-xl border-2 text-sm font-semibold transition-all ${duration === d ? 'border-sage-500 bg-sage-50 text-sage-900' : 'border-cream-300 bg-white text-sage-500 hover:border-sage-300'}`}>{d} min</button>
          ))}
        </div>
      </div>
      <div className="mb-10">
        <label className="block text-sm font-semibold text-sage-700 mb-3">Level</label>
        <div className="grid grid-cols-3 gap-2">
          {([{ value: 'beginner', label: 'Beginner', emoji: '🌱' }, { value: 'intermediate', label: 'Intermediate', emoji: '⭐' }, { value: 'advanced', label: 'Advanced', emoji: '🏆' }] as const).map(l => (
            <button key={l.value} onClick={() => setLevel(l.value)} className={`py-3 rounded-xl border-2 text-sm font-semibold transition-all ${level === l.value ? 'border-sage-500 bg-sage-50 text-sage-900' : 'border-cream-300 bg-white text-sage-500 hover:border-sage-300'}`}>{l.emoji} {l.label}</button>
          ))}
        </div>
      </div>
      <button onClick={() => onStart(format, duration, level)} className="w-full py-4 bg-sage-500 hover:bg-sage-600 text-white font-bold text-base rounded-2xl transition-colors shadow-sm">Build Class Structure →</button>
    </div>
  )
}

// ─── Block Name Editor ────────────────────────────────────────────────────────
function BlockNameEditor({ name, emoji, onNameChange, onEmojiChange }: {
  name: string; emoji: string; onNameChange: (n: string) => void; onEmojiChange: (e: string) => void
}) {
  const [editing, setEditing] = useState(false)
  const [showEmoji, setShowEmoji] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  useEffect(() => { if (editing) inputRef.current?.focus() }, [editing])
  return (
    <div className="flex items-center gap-1.5 min-w-0">
      <div className="relative">
        <button onClick={e => { e.stopPropagation(); setShowEmoji(!showEmoji) }}
          className="text-xl hover:scale-110 transition-transform shrink-0 w-8 h-8 flex items-center justify-center rounded-lg hover:bg-white/50">
          {emoji}
        </button>
        {showEmoji && (
          <div className="absolute top-9 left-0 z-50 bg-white border border-cream-200 rounded-xl shadow-lg p-2 grid grid-cols-5 gap-1 w-40" onClick={e => e.stopPropagation()}>
            {BLOCK_EMOJIS.map(e => (
              <button key={e} onClick={() => { onEmojiChange(e); setShowEmoji(false) }}
                className={`text-base w-7 h-7 flex items-center justify-center rounded-lg hover:bg-sage-50 transition-colors ${e === emoji ? 'bg-sage-100' : ''}`}>{e}</button>
            ))}
          </div>
        )}
      </div>
      {editing ? (
        <input ref={inputRef} value={name} onChange={e => onNameChange(e.target.value)}
          onBlur={() => setEditing(false)}
          onKeyDown={e => { if (e.key === 'Enter') setEditing(false); e.stopPropagation() }}
          onClick={e => e.stopPropagation()}
          className="flex-1 font-display font-bold text-sage-900 text-sm bg-white border border-sage-300 rounded-lg px-2 py-0.5 focus:outline-none min-w-0"/>
      ) : (
        <button onClick={e => { e.stopPropagation(); setEditing(true) }}
          className="flex-1 text-left font-display font-bold text-sage-900 leading-tight text-sm hover:text-sage-600 transition-colors truncate group">
          {name}<span className="ml-1 opacity-0 group-hover:opacity-40 text-xs font-normal">✏️</span>
        </button>
      )}
    </div>
  )
}

// ─── Custom Block BPM Picker ──────────────────────────────────────────────────
function CustomBlockControls({ block, format, level, selectedMovements, onToggle, onBpmRangeChange }: {
  block: ClassBlock
  format: 'mat' | 'reformer'
  level: 'beginner' | 'intermediate' | 'advanced'
  selectedMovements: Movement[]
  onToggle: (m: Movement) => void
  onBpmRangeChange: (min: number, max: number) => void
}) {
  const [movSearch, setMovSearch] = useState('')
  const selectedIds = new Set(selectedMovements.map(m => m.id))
  const targetBpm = selectedMovements.length > 0 ? calcTargetBpm(selectedMovements) : null

  const levelOrder = { beginner: 0, intermediate: 1, advanced: 2 }
  const userLevel = levelOrder[level]

  // All movements for this format/level
  const allMovements = MOVEMENTS.filter(m =>
    (m.format === format || m.format === 'both') &&
    levelOrder[m.level] <= userLevel
  )

  // Filter by search or show all
  const displayed = movSearch.trim()
    ? allMovements.filter(m => m.name.toLowerCase().includes(movSearch.toLowerCase()))
    : allMovements

  // Group by block category for display when not searching
  const grouped = movSearch.trim() ? null : displayed.reduce((acc, m) => {
    const key = m.blocks[0] ?? 'other'
    if (!acc[key]) acc[key] = []
    acc[key].push(m)
    return acc
  }, {} as Record<string, Movement[]>)

  // Human-readable group labels
  const groupLabels: Record<string, string> = {
    warmup: 'Warm Up', standing: 'Standing', floorwork1: 'Floor Work',
    peak: 'Peak Work', cooldown: 'Cool Down',
    footwork: 'Footwork', abdominals: 'Abdominals', legships: 'Legs & Hips',
    upperbody: 'Upper Body', stretch: 'Stretch & Finishing', other: 'Other'
  }

  return (
    <div className="mb-5">
      {/* BPM Range */}
      <div className="mb-5 p-4 bg-sage-50 rounded-xl border border-sage-100">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h4 className="text-sm font-semibold text-sage-700">BPM Range</h4>
            <p className="text-xs text-sage-400">Set the tempo range for songs in this block</p>
          </div>
          {targetBpm && (
            <div className="text-right">
              <div className="text-xs text-sage-400">Target from movements</div>
              <div className="text-lg font-bold text-sage-700">{targetBpm} BPM</div>
            </div>
          )}
        </div>
        <div className="flex items-center gap-3 mb-2">
          <span className="text-xs font-mono text-sage-600 w-8">{block.bpmMin}</span>
          <input type="range" min={60} max={block.bpmMax - 5} value={block.bpmMin}
            onChange={e => onBpmRangeChange(parseInt(e.target.value), block.bpmMax)}
            className="flex-1 accent-sage-500"/>
          <span className="text-xs text-sage-400">min</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs font-mono text-sage-600 w-8">{block.bpmMax}</span>
          <input type="range" min={block.bpmMin + 5} max={200} value={block.bpmMax}
            onChange={e => onBpmRangeChange(block.bpmMin, parseInt(e.target.value))}
            className="flex-1 accent-sage-500"/>
          <span className="text-xs text-sage-400">max</span>
        </div>
        <p className="text-xs text-sage-400 mt-2 text-center">
          Songs filtered to <span className="font-semibold text-sage-600">{block.bpmMin}–{block.bpmMax} BPM</span>
        </p>
      </div>

      {/* Movement browser */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-sm font-semibold text-sage-700">Movements</h4>
          {selectedMovements.length > 0 && (
            <span className="text-xs text-sage-400">{selectedMovements.length} selected</span>
          )}
        </div>
        <p className="text-xs text-sage-400 mb-3">Browse or search — selecting movements auto-updates BPM range</p>

        {/* Search */}
        <div className="relative mb-4">
          <svg className="absolute left-3 top-1/2 -translate-y-1/2 text-sage-300 w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
          <input type="text" value={movSearch} onChange={e => setMovSearch(e.target.value)}
            placeholder="Filter movements..."
            className="w-full pl-8 pr-4 py-2 text-sm bg-white border border-cream-300 rounded-xl text-sage-800 placeholder-sage-300 focus:outline-none focus:border-sage-400"/>
          {movSearch && (
            <button onClick={() => setMovSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-sage-300 hover:text-sage-500">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="2"><path d="M1 1l10 10M11 1L1 11"/></svg>
            </button>
          )}
        </div>

        {/* Movement list — scrollable */}
        <div className="max-h-64 overflow-y-auto space-y-4 pr-1">
          {movSearch.trim() ? (
            // Flat list when searching
            displayed.length === 0 ? (
              <p className="text-xs text-sage-400 italic text-center py-4">No movements found</p>
            ) : (
              <div className="flex flex-wrap gap-2">
                {displayed.map(m => {
                  const selected = selectedIds.has(m.id)
                  return (
                    <button key={m.id} onClick={() => onToggle(m)}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all border ${selected ? 'bg-sage-500 text-white border-sage-500 shadow-sm' : 'bg-white text-sage-600 border-cream-300 hover:border-sage-300 hover:bg-sage-50'}`}>
                      {selected && <span>✓</span>}{m.name}
                      <span className={`font-mono ${selected ? 'text-sage-200' : 'text-sage-400'}`}>{m.bpm}</span>
                    </button>
                  )
                })}
              </div>
            )
          ) : (
            // Grouped by category when not searching
            Object.entries(grouped!).map(([groupKey, groupMovements]) => (
              <div key={groupKey}>
                <p className="text-xs font-semibold text-sage-400 uppercase tracking-wider mb-2">
                  {groupLabels[groupKey] ?? groupKey}
                </p>
                <div className="flex flex-wrap gap-2">
                  {groupMovements.map(m => {
                    const selected = selectedIds.has(m.id)
                    return (
                      <button key={m.id} onClick={() => onToggle(m)}
                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all border ${selected ? 'bg-sage-500 text-white border-sage-500 shadow-sm' : 'bg-white text-sage-600 border-cream-300 hover:border-sage-300 hover:bg-sage-50'}`}>
                        {selected && <span>✓</span>}{m.name}
                        <span className={`font-mono ${selected ? 'text-sage-200' : 'text-sage-400'}`}>{m.bpm}</span>
                      </button>
                    )
                  })}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Template Movement Picker ─────────────────────────────────────────────────
function MovementPicker({ block, format, level, selectedMovements, onToggle }: {
  block: ClassBlock; format: 'mat' | 'reformer'; level: 'beginner' | 'intermediate' | 'advanced'
  selectedMovements: Movement[]; onToggle: (m: Movement) => void
}) {
  const available = getMovementsForBlock(format, block.id, level)
  const selectedIds = new Set(selectedMovements.map(m => m.id))
  const targetBpm = selectedMovements.length > 0 ? calcTargetBpm(selectedMovements) : null
  if (available.length === 0) return null
  return (
    <div className="mb-5">
      <div className="flex items-center justify-between mb-3">
        <div><h4 className="text-sm font-semibold text-sage-700">Movements</h4><p className="text-xs text-sage-400">Select what you're teaching — songs will match</p></div>
        {targetBpm && <div className="text-right"><div className="text-xs text-sage-400">Target BPM</div><div className="text-lg font-bold text-sage-700">{targetBpm}</div></div>}
      </div>
      <div className="flex flex-wrap gap-2">
        {available.map(m => {
          const selected = selectedIds.has(m.id)
          return (
            <button key={m.id} onClick={() => onToggle(m)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium transition-all border ${selected ? 'bg-sage-500 text-white border-sage-500 shadow-sm' : 'bg-white text-sage-600 border-cream-300 hover:border-sage-300 hover:bg-sage-50'}`}>
              {selected && <span>✓</span>}{m.name}
              <span className={`font-mono text-xs ${selected ? 'text-sage-200' : 'text-sage-400'}`}>{m.bpm}</span>
            </button>
          )
        })}
      </div>
    </div>
  )
}

// ─── Block Notes ──────────────────────────────────────────────────────────────
function BlockNotes({ blockId, value, onChange }: { blockId: string; value: string; onChange: (blockId: string, note: string) => void }) {
  return (
    <div className="mb-5">
      <label className="block text-sm font-semibold text-sage-700 mb-2">Teaching Notes</label>
      <textarea value={value} onChange={e => onChange(blockId, e.target.value)}
        placeholder="Cues, reminders, modifications for this block..." rows={3}
        className="w-full px-4 py-3 text-sm bg-white border border-cream-300 rounded-xl text-sage-800 placeholder-sage-300 focus:outline-none focus:border-sage-400 resize-none"/>
    </div>
  )
}

// ─── Block Card ───────────────────────────────────────────────────────────────
function BlockCard({ block, index, isActive, onActivate, onRemoveSong, onUpdateBlock, onDeleteBlock, onMoveBlock, canDelete, totalBlocks, selectedMovements, hasNotes, dragHandleProps }: {
  block: ClassBlock; index: number; isActive: boolean; onActivate: () => void
  onRemoveSong: (playlistId: string) => void
  onUpdateBlock: (id: string, updates: Partial<ClassBlock>) => void
  onDeleteBlock: (id: string) => void
  onMoveBlock: (id: string, dir: 'up' | 'down') => void
  canDelete: boolean; totalBlocks: number
  selectedMovements: Movement[]; hasNotes: boolean
  dragHandleProps?: any
}) {
  // dragHandleProps is passed from SortableBlockCard
  const colors = BLOCK_COLORS[block.color] ?? BLOCK_COLORS.sage
  const blockSeconds = block.songs.reduce((acc, s) => acc + (s.duration ?? 0), 0)
  const fillPct = Math.min(100, Math.round((blockSeconds / block.targetDuration) * 100))
  const blockMins = Math.floor(blockSeconds / 60), blockSecs = String(blockSeconds % 60).padStart(2, '00')
  const targetMins = Math.floor(block.targetDuration / 60)
  const isOver = blockSeconds > block.targetDuration, isFull = fillPct >= 95
  const targetBpm = selectedMovements.length > 0 ? calcTargetBpm(selectedMovements) : null

  return (
    <div className={`rounded-2xl border-2 transition-all ${isActive ? colors.border + ' shadow-md' : 'border-cream-200 hover:border-cream-300'} ${colors.bg}`}>
      <div className="p-4">
        <div className="flex items-start justify-between gap-2 mb-2">
          <div className="flex-1 min-w-0" onClick={onActivate}>
            <div className="flex items-center gap-1.5 mb-1">
              <span className="text-xs font-semibold text-sage-400 uppercase tracking-wider">Block {index + 1}</span>
              {isCustomBlock(block.id) && <span className="text-xs px-1.5 py-0.5 rounded-full bg-sage-100 text-sage-500 font-medium">Custom</span>}
              {isFull && <span className="text-xs font-semibold px-1.5 py-0.5 rounded-full bg-green-100 text-green-700">✓ Full</span>}
              {isOver && <span className="text-xs font-semibold px-1.5 py-0.5 rounded-full bg-red-100 text-red-600">Over</span>}
              {hasNotes && <span className="text-xs">📝</span>}
            </div>
            <BlockNameEditor name={block.name} emoji={block.emoji}
              onNameChange={n => onUpdateBlock(block.id, { name: n })}
              onEmojiChange={e => onUpdateBlock(block.id, { emoji: e })}/>
          </div>
          <div className="flex items-center gap-0.5 shrink-0">
            {/* Drag handle */}
            <div {...(dragHandleProps ?? {})} onClick={e => e.stopPropagation()}
              className="w-6 h-6 flex items-center justify-center rounded cursor-grab active:cursor-grabbing text-sage-200 hover:text-sage-400 transition-colors touch-none">
              <svg width="10" height="14" viewBox="0 0 10 14" fill="currentColor">
                <circle cx="2.5" cy="2.5" r="1.5"/><circle cx="7.5" cy="2.5" r="1.5"/>
                <circle cx="2.5" cy="7" r="1.5"/><circle cx="7.5" cy="7" r="1.5"/>
                <circle cx="2.5" cy="11.5" r="1.5"/><circle cx="7.5" cy="11.5" r="1.5"/>
              </svg>
            </div>
            <button onClick={e => { e.stopPropagation(); onMoveBlock(block.id, 'up') }} disabled={index === 0}
              className="w-6 h-6 flex items-center justify-center rounded text-sage-300 hover:text-sage-600 disabled:opacity-20 transition-colors">
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="2"><path d="M2 7l3-4 3 4"/></svg>
            </button>
            <button onClick={e => { e.stopPropagation(); onMoveBlock(block.id, 'down') }} disabled={index === totalBlocks - 1}
              className="w-6 h-6 flex items-center justify-center rounded text-sage-300 hover:text-sage-600 disabled:opacity-20 transition-colors">
              <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="2"><path d="M2 3l3 4 3-4"/></svg>
            </button>
            {canDelete && (
              <button onClick={e => { e.stopPropagation(); onDeleteBlock(block.id) }}
                className="w-6 h-6 flex items-center justify-center rounded text-sage-200 hover:text-red-400 transition-colors">
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" strokeWidth="2"><path d="M1 1l8 8M9 1L1 9"/></svg>
              </button>
            )}
          </div>
        </div>
        <button onClick={onActivate} className="w-full text-left">
          <div className="flex items-center justify-between mb-2">
            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${colors.badge}`}>
              {targetBpm ? `~${targetBpm} BPM` : `${block.bpmMin}–${block.bpmMax} BPM`}
            </span>
            <div className={`text-sm font-bold ${isOver ? 'text-red-500' : 'text-sage-700'}`}>{blockMins}:{blockSecs} <span className="text-xs font-normal text-sage-400">/ {targetMins}m</span></div>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex-1 h-1.5 bg-white/60 rounded-full overflow-hidden">
              <div className={`h-full rounded-full transition-all ${isOver ? 'bg-red-400' : colors.bar}`} style={{ width: `${fillPct}%` }}/>
            </div>
            <span className="text-xs text-sage-400">{fillPct}%</span>
          </div>
          {/* Inline target duration editor for all blocks */}
          <div className="flex items-center gap-2 mt-2" onClick={e => e.stopPropagation()}>
            <span className="text-xs text-sage-400">Target:</span>
            <select
              value={block.targetDuration}
              onChange={e => onUpdateBlock(block.id, { targetDuration: parseInt(e.target.value) })}
              className="text-xs bg-white/70 border border-white/60 rounded-lg px-1.5 py-0.5 text-sage-600 focus:outline-none focus:border-sage-300">
              {[2,3,4,5,6,7,8,9,10,12,15,20].map(m => (
                <option key={m} value={m * 60}>{m} min</option>
              ))}
            </select>
            {isCustomBlock(block.id) && (
              <>
                <span className="text-xs text-sage-400 ml-1">BPM:</span>
                <input type="number" min={60} max={200} value={block.bpmMin}
                  onChange={e => onUpdateBlock(block.id, { bpmMin: parseInt(e.target.value) || 60 })}
                  className="w-12 text-xs bg-white/70 border border-white/60 rounded-lg px-1.5 py-0.5 text-sage-600 focus:outline-none focus:border-sage-300 text-center"/>
                <span className="text-xs text-sage-300">–</span>
                <input type="number" min={60} max={200} value={block.bpmMax}
                  onChange={e => onUpdateBlock(block.id, { bpmMax: parseInt(e.target.value) || 120 })}
                  className="w-12 text-xs bg-white/70 border border-white/60 rounded-lg px-1.5 py-0.5 text-sage-600 focus:outline-none focus:border-sage-300 text-center"/>
              </>
            )}
          </div>
          {selectedMovements.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-1">
              {selectedMovements.slice(0, 3).map(m => <span key={m.id} className="text-xs bg-white/70 text-sage-600 px-2 py-0.5 rounded-full">{m.name}</span>)}
              {selectedMovements.length > 3 && <span className="text-xs text-sage-400">+{selectedMovements.length - 3} more</span>}
            </div>
          )}
        </button>
      </div>
      {block.songs.length > 0 && (
        <div className="px-4 pb-3 space-y-1.5 border-t border-white/60 pt-3">
          {block.songs.map((song, i) => {
            const dur = song.duration ?? 0, m = Math.floor(dur / 60), s = String(dur % 60).padStart(2, '0')
            return (
              <div key={song.playlistId} className="flex items-center gap-2 group bg-white/70 rounded-xl px-3 py-2">
                <span className="text-xs text-sage-300 w-4 shrink-0">{i + 1}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-sage-800 truncate">{song.title ?? song.name}</p>
                  <p className="text-xs text-sage-400 truncate">{song.artist}</p>
                </div>
                <span className="text-xs font-mono text-sage-500 shrink-0">{song.bpm}</span>
                <span className="text-xs text-sage-300 shrink-0">{m}:{s}</span>
                <button onClick={e => { e.stopPropagation(); onRemoveSong(song.playlistId) }}
                  className="text-sage-200 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100 shrink-0">
                  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2"><path d="M2 2l10 10M12 2L2 12"/></svg>
                </button>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}



// ─── Sortable Block Card Wrapper ──────────────────────────────────────────────
function SortableBlockCard(props: Parameters<typeof BlockCard>[0]) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: props.block.id })
  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
    zIndex: isDragging ? 50 : undefined,
  }
  return (
    <div ref={setNodeRef} style={style}>
      <BlockCard {...props} dragHandleProps={{ ...attributes, ...listeners }}/>
    </div>
  )
}
// ─── Equipment Checklist ──────────────────────────────────────────────────────
function EquipmentChecklist({ format, selected, onToggle }: { format: 'mat' | 'reformer'; selected: Set<string>; onToggle: (id: string) => void }) {
  const items = format === 'mat' ? MAT_EQUIPMENT : REFORMER_EQUIPMENT
  return (
    <div className="bg-cream-50 rounded-2xl border border-cream-200 p-4">
      <h3 className="font-display font-bold text-sage-900 mb-3">Equipment Needed</h3>
      <div className="grid grid-cols-2 gap-2">
        {items.map(item => {
          const checked = selected.has(item.id)
          return (
            <button key={item.id} onClick={() => onToggle(item.id)}
              className={`flex items-center gap-2 px-3 py-2 rounded-xl border text-sm font-medium transition-all ${checked ? 'bg-sage-500 text-white border-sage-500' : 'bg-white text-sage-600 border-cream-300 hover:border-sage-300'}`}>
              <span>{item.emoji}</span><span className="truncate">{item.label}</span>
              {checked && <span className="ml-auto text-xs">✓</span>}
            </button>
          )
        })}
      </div>
    </div>
  )
}

// ─── Summary Panel ────────────────────────────────────────────────────────────
function SummaryPanel({ blocks, blockMovements, targetDuration, className, savedId, saveStatus, onSave, onCopy, onExportPDF, onReset }: {
  blocks: ClassBlock[]; blockMovements: Record<string, Movement[]>; targetDuration: number; className: string
  savedId: string | null; saveStatus: 'idle' | 'saving' | 'saved' | 'error'
  onSave: () => void; onCopy: () => void; onExportPDF: () => void; onReset: () => void
}) {
  const totalSeconds = blocks.reduce((acc, b) => acc + b.songs.reduce((a, s) => a + (s.duration ?? 0), 0), 0)
  const totalMins = Math.floor(totalSeconds / 60), totalSecs = String(totalSeconds % 60).padStart(2, '00')
  const pct = Math.min(100, Math.round((totalSeconds / (targetDuration * 60)) * 100))
  const allSongs = blocks.flatMap(b => b.songs)
  const avgBpm = allSongs.length ? Math.round(allSongs.reduce((a, s) => a + s.bpm, 0) / allSongs.length) : 0
  const isOver = totalSeconds > targetDuration * 60
  return (
    <div className="bg-cream-50 rounded-2xl border border-cream-200 p-4 space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="font-display font-bold text-sage-900">Class Summary</h3>
        <button onClick={onReset} className="text-xs text-sage-300 hover:text-red-400 transition-colors">Reset</button>
      </div>
      <div>
        <div className="flex justify-between items-baseline mb-1.5">
          <span className={`text-2xl font-bold ${isOver ? 'text-red-500' : 'text-sage-900'}`}>{totalMins}:{totalSecs}</span>
          <span className="text-sm text-sage-400">/ {targetDuration}m target</span>
        </div>
        <div className="h-2 bg-cream-200 rounded-full overflow-hidden">
          <div className={`h-full rounded-full transition-all ${isOver ? 'bg-red-400' : 'bg-sage-400'}`} style={{ width: `${pct}%` }}/>
        </div>
        <div className="flex justify-between mt-1">
          <span className="text-xs text-sage-400">{pct}% filled</span>
          {avgBpm > 0 && <span className="text-xs text-sage-400">avg {avgBpm} BPM</span>}
        </div>
      </div>
      <div>
        <p className="text-xs font-semibold text-sage-500 uppercase tracking-wider mb-2">Energy Arc</p>
        <EnergyArc blocks={blocks} blockMovements={blockMovements}/>
      </div>
      <div className="space-y-1.5">
        {blocks.map(b => {
          const bSecs = b.songs.reduce((a, s) => a + (s.duration ?? 0), 0)
          const bMins = Math.floor(bSecs / 60), bSec = String(bSecs % 60).padStart(2, '0')
          const colors = BLOCK_COLORS[b.color] ?? BLOCK_COLORS.sage
          return (
            <div key={b.id} className="flex items-center gap-2 text-xs">
              <span>{b.emoji}</span>
              <span className="flex-1 text-sage-600 truncate">{b.name}</span>
              <span className={`font-mono font-semibold px-1.5 py-0.5 rounded ${colors.badge}`}>{bMins}:{bSec}</span>
            </div>
          )
        })}
      </div>
      {allSongs.length > 0 && (
        <div className="space-y-2">
          <button onClick={onSave} disabled={saveStatus === 'saving'}
            className={`w-full py-2.5 font-semibold text-sm rounded-xl transition-colors ${saveStatus === 'saved' ? 'bg-green-500 text-white' : saveStatus === 'error' ? 'bg-red-400 text-white' : 'bg-sage-500 hover:bg-sage-600 text-white'}`}>
            {saveStatus === 'saving' ? '⏳ Saving...' : saveStatus === 'saved' ? '✓ Saved!' : saveStatus === 'error' ? '✗ Error — try again' : savedId ? '💾 Update Saved Class' : '💾 Save Class'}
          </button>
          <button onClick={onExportPDF} className="w-full py-2.5 bg-sage-700 hover:bg-sage-800 text-white font-semibold text-sm rounded-xl transition-colors">📄 Export as PDF</button>
          <button onClick={onCopy} className="w-full py-2.5 bg-white hover:bg-sage-50 border border-sage-200 text-sage-700 font-semibold text-sm rounded-xl transition-colors">📋 Copy Class Plan</button>
        </div>
      )}
    </div>
  )
}

// ─── Main ClassBuilder ────────────────────────────────────────────────────────
export default function ClassBuilder() {
  const { isSignedIn } = useUser()
  const [setup, setSetup] = useState<{ format: 'mat' | 'reformer'; duration: number; level: 'beginner' | 'intermediate' | 'advanced' } | null>(null)
  const [blocks, setBlocks] = useState<ClassBlock[]>([])
  const [activeBlockId, setActiveBlockId] = useState<string | null>(null)
  const [blockMovements, setBlockMovements] = useState<Record<string, Movement[]>>({})
  const [blockNotes, setBlockNotes] = useState<Record<string, string>>({})
  const [equipment, setEquipment] = useState<Set<string>>(new Set())
  const [songs, setSongs] = useState<Song[]>([])
  const [search, setSearch] = useState('')
  const [sortBy, setSortBy] = useState('default')
  const [loading, setLoading] = useState(false)
  const [className, setClassName] = useState('My Pilates Class')
  const [savedId, setSavedId] = useState<string | null>(null)
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')
  const [savedClasses, setSavedClasses] = useState<any[]>([])
  const [songSource, setSongSource] = useState<'library' | 'spotify'>('library')
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }))

  const activeBlock = blocks.find(b => b.id === activeBlockId) ?? null
  const activeMovements = activeBlockId ? (blockMovements[activeBlockId] ?? []) : []

  useEffect(() => {
    if (!isSignedIn) return
    fetch('/api/playlists').then(r => r.json()).then(data => { if (Array.isArray(data)) setSavedClasses(data) }).catch(() => {})
  }, [isSignedIn])

  useEffect(() => {
    if (!activeBlock || !setup) return
    setLoading(true)
    const movements = blockMovements[activeBlock.id] ?? []
    const [minBpm, maxBpm] = isCustomBlock(activeBlock.id)
      ? [activeBlock.bpmMin, activeBlock.bpmMax]
      : bpmRangeFromMovements(movements, activeBlock.bpmMin, activeBlock.bpmMax)
    const params = new URLSearchParams()
    params.set('minBpm', minBpm.toString()); params.set('maxBpm', maxBpm.toString())
    fetch(`/api/songs?${params}`).then(r => r.json()).then(data => { setSongs(data); setLoading(false) })
  }, [activeBlockId, blockMovements, blocks])

  function handleStart(format: 'mat' | 'reformer', duration: number, level: 'beginner' | 'intermediate' | 'advanced') {
    const template = generateTemplate(format, duration, level)
    const newBlocks: ClassBlock[] = template.map(t => ({ ...t, songs: [] }))
    setBlocks(newBlocks); setSetup({ format, duration, level })
    setActiveBlockId(newBlocks[0].id); setBlockMovements({})
    setBlockNotes({}); setEquipment(new Set()); setSavedId(null); setSaveStatus('idle')
  }

  function handleLoad(saved: any) {
    const d = saved.data
    setBlocks(d.blocks); setBlockMovements(d.blockMovements ?? {})
    setBlockNotes(d.blockNotes ?? {}); setEquipment(new Set(d.equipment ?? []))
    setSetup({ format: saved.format, duration: saved.duration, level: saved.level })
    setClassName(saved.name); setSavedId(saved.id); setSaveStatus('idle')
    setActiveBlockId(d.blocks[0]?.id ?? null)
  }

  async function handleDelete(id: string) {
    await fetch(`/api/playlists?id=${id}`, { method: 'DELETE' })
    setSavedClasses(prev => prev.filter(c => c.id !== id))
  }

  async function handleSave() {
    if (!isSignedIn) { alert('Please sign in to save your class.'); return }
    setSaveStatus('saving')
    const payload = { id: savedId, name: className, format: setup?.format, duration: setup?.duration, level: setup?.level, data: { blocks, blockMovements, blockNotes, equipment: Array.from(equipment) } }
    try {
      const res = await fetch('/api/playlists', { method: savedId ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setSavedId(data.id); setSaveStatus('saved')
      fetch('/api/playlists').then(r => r.json()).then(d => { if (Array.isArray(d)) setSavedClasses(d) })
      setTimeout(() => setSaveStatus('idle'), 3000)
    } catch { setSaveStatus('error'); setTimeout(() => setSaveStatus('idle'), 3000) }
  }

  async function handleExportPDF() {
    if (!setup) return
    try { await exportToPDF(className, setup, blocks, blockMovements, blockNotes, equipment) }
    catch (e) { console.error('PDF export error:', e); alert('PDF export failed. Please try again.') }
  }

  function updateBlock(id: string, updates: Partial<ClassBlock>) {
    setBlocks(prev => prev.map(b => b.id === id ? { ...b, ...updates } : b))
  }

  function deleteBlock(id: string) {
    setBlocks(prev => { const next = prev.filter(b => b.id !== id); if (activeBlockId === id) setActiveBlockId(next[0]?.id ?? null); return next })
    setBlockMovements(prev => { const next = { ...prev }; delete next[id]; return next })
    setBlockNotes(prev => { const next = { ...prev }; delete next[id]; return next })
  }

  function moveBlock(id: string, dir: 'up' | 'down') {
    setBlocks(prev => {
      const idx = prev.findIndex(b => b.id === id)
      if (idx === -1) return prev
      const next = [...prev]
      const swap = dir === 'up' ? idx - 1 : idx + 1
      if (swap < 0 || swap >= next.length) return prev;
      [next[idx], next[swap]] = [next[swap], next[idx]]
      return next
    })
  }

  function addBlock() {
    const colorKey = COLOR_KEYS[blocks.length % COLOR_KEYS.length]
    const newBlock: ClassBlock = {
      id: `custom-${Date.now()}`,
      name: 'New Block',
      emoji: BLOCK_EMOJIS[blocks.length % BLOCK_EMOJIS.length],
      description: 'Custom block',
      bpmMin: 80, bpmMax: 120,
      targetDuration: 600,
      color: colorKey as any,
      songs: [],
    }
    setBlocks(prev => [...prev, newBlock])
    setActiveBlockId(newBlock.id)
  }

  function toggleMovement(blockId: string, movement: Movement) {
    setBlockMovements(prev => {
      const current = prev[blockId] ?? []
      const exists = current.find(m => m.id === movement.id)
      const updated = exists ? current.filter(m => m.id !== movement.id) : [...current, movement]
      // For custom blocks, auto-update BPM range based on movements
      if (isCustomBlock(blockId) && updated.length > 0) {
        const avg = Math.round(updated.reduce((a, m) => a + m.bpm, 0) / updated.length)
        const newMin = Math.max(60, avg - 12), newMax = Math.min(200, avg + 12)
        setBlocks(bPrev => bPrev.map(b => b.id === blockId ? { ...b, bpmMin: newMin, bpmMax: newMax } : b))
      }
      return { ...prev, [blockId]: updated }
    })
  }

  function updateNote(blockId: string, note: string) { setBlockNotes(prev => ({ ...prev, [blockId]: note })) }
  function toggleEquipment(id: string) { setEquipment(prev => { const next = new Set(prev); next.has(id) ? next.delete(id) : next.add(id); return next }) }

  function addSongToBlock(song: Song) {
    if (!activeBlockId) return
    setBlocks(prev => prev.map(b => b.id === activeBlockId ? { ...b, songs: [...b.songs, { ...song, playlistId: `${song.id}-${Date.now()}` }] } : b))
  }

  function removeSongFromBlock(blockId: string, playlistId: string) {
    setBlocks(prev => prev.map(b => b.id === blockId ? { ...b, songs: b.songs.filter(s => s.playlistId !== playlistId) } : b))
  }

  function copyFullClass() {
    if (!setup) return
    const equipmentList = Array.from(equipment).map(id => (setup.format === 'mat' ? MAT_EQUIPMENT : REFORMER_EQUIPMENT).find(e => e.id === id)?.label).filter(Boolean).join(', ')
    const lines = [`${className}`, `${setup.format === 'mat' ? '🧘 Mat' : '⚙️ Reformer'} Pilates — ${setup.duration} min — ${setup.level.charAt(0).toUpperCase() + setup.level.slice(1)}`, '', ...(equipmentList ? [`📦 Equipment: ${equipmentList}`, ''] : []), ...blocks.flatMap(b => { const movements = blockMovements[b.id] ?? []; const note = blockNotes[b.id] ?? ''; const bSecs = b.songs.reduce((a, s) => a + (s.duration ?? 0), 0); const bMins = Math.floor(bSecs / 60); const bSec = String(bSecs % 60).padStart(2, '0'); return [`${b.emoji} ${b.name} (${bMins}:${bSec})`, ...(movements.length > 0 ? [`   Movements: ${movements.map(m => m.name).join(', ')}`] : []), ...(note ? [`   Notes: ${note}`] : []), ...b.songs.map((s, i) => { const dur = s.duration ?? 0; const m = Math.floor(dur / 60); const sec = String(dur % 60).padStart(2, '0'); return `   ${i + 1}. ${s.title ?? s.name} — ${s.artist} (${s.bpm} BPM, ${m}:${sec})` }), ''] })]
    navigator.clipboard.writeText(lines.join('\n'))
  }

  const searchedSongs = search.trim() ? songs.filter(s => s.title.toLowerCase().includes(search.toLowerCase()) || s.artist.toLowerCase().includes(search.toLowerCase())) : songs
  const filteredSongs = [...searchedSongs].sort((a, b) => { if (sortBy === 'bpm-asc') return a.bpm - b.bpm; if (sortBy === 'bpm-desc') return b.bpm - a.bpm; if (sortBy === 'duration-asc') return (a.duration ?? 0) - (b.duration ?? 0); if (sortBy === 'duration-desc') return (b.duration ?? 0) - (a.duration ?? 0); return 0 })
  const addedIds = new Set(blocks.flatMap(b => b.songs.map(s => s.id)))

  const activeBpmRange = activeBlock
    ? isCustomBlock(activeBlock.id)
      ? [activeBlock.bpmMin, activeBlock.bpmMax]
      : bpmRangeFromMovements(activeMovements, activeBlock.bpmMin, activeBlock.bpmMax)
    : [85, 100]

  if (!setup) return <SetupScreen onStart={handleStart} savedClasses={savedClasses} onLoad={handleLoad} onDelete={handleDelete}/>

  return (
    <div className="flex gap-6">
      <div className="w-80 shrink-0 space-y-3">
        <div className="bg-cream-50 rounded-2xl border border-cream-200 px-4 py-3">
          <label className="block text-xs font-semibold text-sage-500 uppercase tracking-wider mb-1.5">Class Name</label>
          <input value={className} onChange={e => setClassName(e.target.value)}
            className="w-full text-sm font-semibold text-sage-900 bg-transparent focus:outline-none placeholder-sage-300" placeholder="My Pilates Class"/>
        </div>
        <SummaryPanel blocks={blocks} blockMovements={blockMovements} targetDuration={setup.duration} className={className} savedId={savedId} saveStatus={saveStatus} onSave={handleSave} onCopy={copyFullClass} onExportPDF={handleExportPDF}
          onReset={() => { setSetup(null); setBlocks([]); setActiveBlockId(null); setBlockMovements({}); setBlockNotes({}); setEquipment(new Set()); setSavedId(null) }}/>
        <EquipmentChecklist format={setup.format} selected={equipment} onToggle={toggleEquipment}/>
        <DndContext sensors={sensors} collisionDetection={closestCenter}
          onDragEnd={(event: DragEndEvent) => {
            const { active, over } = event
            if (over && active.id !== over.id) {
              const oldIdx = blocks.findIndex(b => b.id === active.id)
              const newIdx = blocks.findIndex(b => b.id === over.id)
              setBlocks(arrayMove(blocks, oldIdx, newIdx))
            }
          }}>
          <SortableContext items={blocks.map(b => b.id)} strategy={verticalListSortingStrategy}>
            {blocks.map((block, i) => (
              <SortableBlockCard key={block.id} block={block} index={i} isActive={activeBlockId === block.id}
                onActivate={() => { setActiveBlockId(block.id); setSearch(''); setSortBy('default') }}
                onRemoveSong={pid => removeSongFromBlock(block.id, pid)}
                onUpdateBlock={updateBlock} onDeleteBlock={deleteBlock} onMoveBlock={moveBlock}
                canDelete={blocks.length > 1} totalBlocks={blocks.length}
                selectedMovements={blockMovements[block.id] ?? []}
                hasNotes={!!(blockNotes[block.id]?.trim())}/>
            ))}
          </SortableContext>
        </DndContext>
        <button onClick={addBlock}
          className="w-full py-3 border-2 border-dashed border-cream-300 rounded-2xl text-sm font-medium text-sage-400 hover:border-sage-300 hover:text-sage-600 hover:bg-sage-50 transition-all flex items-center justify-center gap-2">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2"><path d="M7 1v12M1 7h12"/></svg>
          Add Block
        </button>
      </div>

      <div className="flex-1 min-w-0">
        {activeBlock && setup ? (
          <>
            <div className="bg-cream-50 border border-cream-200 rounded-2xl p-5 mb-5">
              {isCustomBlock(activeBlock.id) ? (
                <CustomBlockControls
                  block={activeBlock}
                  format={setup.format}
                  level={setup.level}
                  selectedMovements={activeMovements}
                  onToggle={m => toggleMovement(activeBlock.id, m)}
                  onBpmRangeChange={(min, max) => updateBlock(activeBlock.id, { bpmMin: min, bpmMax: max })}
                />
              ) : (
                <>
                  <MovementPicker block={activeBlock} format={setup.format} level={setup.level} selectedMovements={activeMovements} onToggle={m => toggleMovement(activeBlock.id, m)}/>
                  {activeMovements.length === 0 && <p className="text-xs text-sage-400 italic mb-5">No movements selected — showing songs in the {activeBlock.bpmMin}–{activeBlock.bpmMax} BPM range. Select movements to refine.</p>}
                </>
              )}
              <BlockNotes blockId={activeBlock.id} value={blockNotes[activeBlock.id] ?? ''} onChange={updateNote}/>
            </div>

            {/* Source tabs + controls */}
            <div className="flex items-center gap-3 mb-4 flex-wrap">
              <div>
                <h3 className="font-display font-bold text-sage-900 text-lg">{activeBlock.emoji} {activeBlock.name}</h3>
                <p className="text-sm text-sage-400">
                  {activeBpmRange[0]}–{activeBpmRange[1]} BPM
                  {!isCustomBlock(activeBlock.id) && activeMovements.length > 0 ? ` · based on ${activeMovements.length} movement${activeMovements.length > 1 ? 's' : ''}` : ''}
                </p>
              </div>
              <div className="ml-auto flex items-center gap-2">
                <div className="inline-flex items-center bg-cream-100 rounded-xl p-1 gap-0.5 border border-cream-200">
                  <button onClick={() => setSongSource('library')}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${songSource === 'library' ? 'bg-white text-sage-900 shadow-sm font-semibold' : 'text-sage-500 hover:text-sage-700'}`}>
                    Library
                  </button>
                  <button onClick={() => setSongSource('spotify')}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all flex items-center gap-1.5 ${songSource === 'spotify' ? 'bg-white text-sage-900 shadow-sm font-semibold' : 'text-sage-500 hover:text-sage-700'}`}>
                    <svg width="10" height="10" viewBox="0 0 24 24" fill="#1DB954"><path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/></svg>
                    My Playlists
                  </button>
                </div>
                {songSource === 'library' && (
                  <>
                    <select value={sortBy} onChange={e => setSortBy(e.target.value)} className="px-3 py-2 text-sm bg-white border border-cream-300 rounded-xl text-sage-700 focus:outline-none focus:border-sage-400">
                      <option value="default">Sort: Default</option>
                      <option value="bpm-asc">BPM: Low → High</option>
                      <option value="bpm-desc">BPM: High → Low</option>
                      <option value="duration-asc">Duration: Shortest</option>
                      <option value="duration-desc">Duration: Longest</option>
                    </select>
                    <div className="relative">
                      <svg className="absolute left-3 top-1/2 -translate-y-1/2 text-sage-300 w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
                      <input type="text" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search songs..."
                        className="pl-9 pr-4 py-2 text-sm bg-white border border-cream-300 rounded-xl text-sage-800 placeholder-sage-300 focus:outline-none focus:border-sage-400 w-48"/>
                    </div>
                  </>
                )}
              </div>
            </div>

            {songSource === 'spotify' ? (
              <SpotifyPlaylistPicker
                activeBpmMin={activeBpmRange[0]}
                activeBpmMax={activeBpmRange[1]}
                addedIds={addedIds}
                onAdd={addSongToBlock}
              />
            ) : loading ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">{[...Array(6)].map((_, i) => <div key={i} className="h-40 rounded-2xl bg-cream-100 animate-pulse"/>)}</div>
            ) : filteredSongs.length === 0 ? (
              <div className="text-center py-16"><div className="text-4xl mb-3">🔍</div><p className="text-sage-500">No songs found in {activeBpmRange[0]}–{activeBpmRange[1]} BPM range</p></div>
            ) : (
              <>
                <p className="text-sm text-sage-500 mb-3"><span className="font-semibold text-sage-700">{filteredSongs.length}</span> songs found</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
                  {filteredSongs.map(song => <SongCard key={song.id} song={song} isInPlaylist={addedIds.has(song.id)} onAdd={addSongToBlock}/>)}
                </div>
              </>
            )}
          </>
        ) : (
          <div className="flex flex-col items-center justify-center h-64 text-center">
            <div className="text-4xl mb-3">👈</div>
            <p className="text-sage-500 font-medium">Select a block to start adding songs</p>
          </div>
        )}
      </div>
    </div>
  )
}
